
services:
  tidb:
      image: pingcap/tidb:latest
      container_name: chu-tidb
      restart: unless-stopped
      environment:
        TIDB_USER: chutest
        TIDB_PASSWORD: chutest123
        TIDB_DB: test
      ports:
        - "4000:4000"  
        - "10080:10080" 
      command:
        - --store=unistore
        - --path=/tmp/tidb
        - -L=info

      volumes:
        - tidb_data:/tmp/tidb

volumes:
  tidb_data: